### PR TITLE
Update gemspec version to 0.0.14

### PR DESCRIPTION
**Pull request by marcin-cb**
### What changed? Why?

Prep for v0.0.14 release

### CODE REVIEW

**Review by jazz-cb — APPROVED** [review]

**Review by John-peterson-coinbase — CHANGES_REQUESTED** [review]
please add changelog for this version

**Comment by deangalvin-cb** [comment]
@John-peterson-coinbase I opened: https://github.com/coinbase/coinbase-sdk-ruby/pull/127
Im wondering if we should update the changelog there instead? I can just add a commit if desired.

**Comment by John-peterson-coinbase** [comment]
@deangalvin-cb we can do it in #127 if you prefer!

**Comment by marcin-cb** [comment]
> @John-peterson-coinbase I opened: #127 Im wondering if we should update the changelog there instead? I can just add a commit if desired.

Yeah go for it @deangalvin-cb , I can close this.

**Review by John-peterson-coinbase — APPROVED** [review]

**Review by deangalvin-cb — APPROVED** [review]

**Pull request merged**
