### PR TITLE
V0.0.10 release

### PR DESCRIPTION
**Pull request by jazz-cb**
### Added

- Add support for Dedicated ETH Staking for external addresses
- Add support for listing validator details and fetch details of a specific validator

### Changed

- Improved accessibility for `StakingReward` and `StakingOperation` classes

### CODE REVIEW

**Review by alex-stone — APPROVED** [review]

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-ruby/issues/113) to review and +1

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-ruby/issues/113) to review and +1

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-ruby/issues/113) to review and +1

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-ruby/issues/113) to review and +1

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/coinbase-sdk-ruby/issues/113) to review and +1

**Pull request merged**
